name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build
      working-directory: cmd/GitLabFileDownloader
      run: go build -v .

    - name: Test
      working-directory: cmd/GitLabFileDownloader
      run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic .

    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v4
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
        
